### ISSUE TITLE
The game is completely broken for me

### ISSUE THREAD

**Issue by ducksmatter** [apollovy/Cataclysm-DDA-iOS#3]
I put in a bug report on Atlassian but I can’t guarantee that it will be seen by the developer.

both links to the footage of my game having a demented mental breakdown and link to the issue will be here

[Atlassian Bug Report](https://apollov.atlassian.net/servicedesk/customer/portal/6/SSCE-1?created=true) 
[YouTube Video of reported bugs](https://youtu.be/8nojheRasOI) 

Also the debug log in the files because I’m not Mr. Tech Know It All
[
[debug.log](https://github.com/apollovy/Cataclysm-DDA-iOS/files/11046157/debug.log)
](url)

**Comment by apollovy** [comment]
I have answered at the support site.
Strange, but I really didn't receive an email about your application, possibly because it was created for my another project. So thank you that you finally found a way to reach me :)
