### ISSUE TITLE
Build on jailbroken ipad

### ISSUE THREAD

**Issue by tonn333** [apollovy/Cataclysm-DDA-iOS#7]
Is it possible to build a working version (any version) on my jailbroken iPad pro 2020?
I have ish and other terminal emulators on it.
Some weird bug, that I'm unable to solve, doesn't allow me to download any new apps from the appstore. 
So building one would be my only option to fulfill my dream of playing cataclysm on my only device.

**Comment by apollovy** [comment]
While it might be possible, I bet it would be way too complicated to do it.
You could try resetting your device and setting it up from scratch to resolve your nasty bug.
